### ISSUE TITLE
[BUG] TypoScript condition is wrong

### ISSUE THREAD

**Issue by instruccionesaldorso** [pixelant/pxa_cookie_bar#18]
According to https://docs.typo3.org/m/typo3/reference-typoscript/10.4/en-us/Conditions/#constant, 

this TypoScript condition under Configuration/TypoScript/setup.txt is not working anymore for TYPO3 10.4 compatibility:

[globalVar = LIT:bottom={$plugin.tx_pxacookiebar.settings.position}]

It should be:

["{$plugin.tx_pxacookiebar.settings.position}" == "bottom"] 

Would you mind fixing it?

**Comment by MattiasNilsson** [comment]
@instruccionesaldorso Solved with this PR: https://github.com/pixelant/pxa_cookie_bar/pull/21
